#!/usr/bin/env ruby

require File.expand_path('../../../config/application', __FILE__)
Rails.application.require_environment!

require "#{Rails.root}/app/workers/copy_image"

class CopyImageDaemon < DaemonSpawn::Base
  def start(args)
    @worker = Resque::Worker.new('copy_image')
    @worker.verbose = true
    @worker.work
  end

  def stop
    @worker.try(:shutdown)
  end
end

CopyImageDaemon.spawn!({
  processes: 1,
  working_dir: Rails.root,
  pid_file: File.join(Rails.root, 'tmp', 'pids', 'copy_image.pid'),
  log_file: File.join(Rails.root, 'log', 'copy_image.log'),
  sync_log: true,
  singleton: true,
  signal: 'QUIT'
})