#!/usr/bin/env ruby

require File.expand_path('../../../config/application', __FILE__)
Rails.application.require_environment!

require "#{Rails.root}/app/workers/detect_illust"

class DetectIllustDaemon < DaemonSpawn::Base
  def start(args)
    @worker = Resque::Worker.new('detect_illust')
    #@worker.verbose = true
    @worker.work
  end

  def stop
    @worker.try(:shutdown)
  end
end

DetectIllustDaemon.spawn!({
  processes: 2,
  working_dir: Rails.root,
  pid_file: File.join(Rails.root, 'tmp', 'pids', 'detect_illust.pid'),
  #log_file: File.join(Rails.root, 'log', 'detect_illust.log'),
  #sync_log: true,
  singleton: true,
  signal: 'QUIT'
})