#!/usr/bin/env ruby

require File.expand_path('../../../config/application', __FILE__)
Rails.application.require_environment!

require "#{Rails.root}/app/workers/download_image_large"

class DownloadImageLargeDaemon < DaemonSpawn::Base
  def start(args)
    @worker = Resque::Worker.new('download_image_large')
    @worker.work
  end

  def stop
    @worker.try(:shutdown)
  end
end

DownloadImageLargeDaemon.spawn!({
  processes: 1,
  working_dir: Rails.root,
  pid_file: File.join(Rails.root, 'tmp', 'pids', 'download_image.pid'),
  log_file: File.join(Rails.root, 'log', 'download_image.log'),
  sync_log: true,
  singleton: true,
  signal: 'QUIT'
})