#!/usr/bin/env ruby

require File.expand_path('../../../config/application', __FILE__)
Rails.application.require_environment!

require "#{Rails.root}/app/workers/download_image"

class DownloadImageDaemon < DaemonSpawn::Base
  def start(args)
    @worker = Resque::Worker.new('download_image')
    @worker.work(0.1)
  end

  def stop
    @worker.try(:shutdown)
  end
end

DownloadImageDaemon.spawn!({
  processes: 4,
  working_dir: Rails.root,
  pid_file: File.join(Rails.root, 'tmp', 'pids', 'download_image.pid'),
  log: false,
  singleton: true,
  signal: 'QUIT'
})