#!/usr/bin/env ruby

require File.expand_path('../../../config/application', __FILE__)
Rails.application.require_environment!

require "#{Rails.root}/app/workers/image_feature"

class ImageFeatureDaemon < DaemonSpawn::Base
  def start(args)
    @worker = Resque::Worker.new('image_feature')
    @worker.work
  end

  def stop
    @worker.try(:shutdown)
  end
end

ImageFeatureDaemon.spawn!({
  processes: 2,
  working_dir: Rails.root,
  pid_file: File.join(Rails.root, 'tmp', 'pids', 'images_feature.pid'),
  log: false,
  #log_file: File.join(Rails.root, 'log', 'images_face.log'),
  #sync_log: true,
  singleton: true,
  signal: 'QUIT'
})