#!/usr/bin/env ruby

require File.expand_path('../../../config/application', __FILE__)
Rails.application.require_environment!

require "#{Rails.root}/app/workers/target_images_face"

class TargetFaceDaemon < DaemonSpawn::Base
  def start(args)
    @worker = Resque::Worker.new('target_face')
    @worker.work
  end

  def stop
    @worker.try(:shutdown)
  end
end

TargetFaceDaemon.spawn!({
  processes: 1,
  working_dir: Rails.root,
  pid_file: File.join(Rails.root, 'tmp', 'pids', 'target_face.pid'),
  log_file: File.join(Rails.root, 'log', 'target_face.log'),
  sync_log: true,
  singleton: true,
  signal: 'QUIT'
})