#!/usr/bin/env ruby

require File.expand_path('../../config/application', __FILE__)
Rails.application.require_environment!

require "#{Rails.root}/app/workers/images_face"
require "#{Rails.root}/app/workers/target_images_face"

class ResqueWorkerDaemon < DaemonSpawn::Base
  def start(args)
    #@worker = Resque::Worker.new('resque_face, image_face')
    @worker = Resque::Worker.new('*')
    @worker.verbose = true
    @worker.work
  end

  def stop
    @worker.try(:shutdown)
  end
end

ResqueWorkerDaemon.spawn!({
  processes: 1,
  :working_dir => Rails.root,
  :pid_file => File.join(Rails.root, 'tmp', 'pids', 'extract_features.pid'),
  :log_file => File.join(Rails.root, 'log', 'extract_features.log'),
  :sync_log => true,
  :singleton => true,
  :signal => 'QUIT'
})